server:
  port: 8888

spring:
  application:
    name: factory-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/factory-msa/factory-config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
